framework: mocha  
preRun:
  command:
    - yarn install
postMerge:
  pattern:
    - "./test/index.js"
preMerge:
  pattern:
    - "./test/index.js"
postRun:
  command:
    - yarn --version # Mention post-run steps here
version: 1.0
