---
framework: mocha  
preRun:
  command:
    - yarn install
preMerge:
  pattern:
    - "./test/index.js"
postMerge:
  pattern:
    - "./test/index.js"
postRun:
  command:
    - yarn --version
version: 1.0
